# Generated by Django 4.2.20 on 2025-04-29 19:45

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_location_name_ci'),
        ),
    ]
